// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_victory_road = "CgkIj7XW1fQbEAIQCA"; // <GPGSID>
        public const string achievement_hero = "CgkIj7XW1fQbEAIQBA"; // <GPGSID>
        public const string achievement_grim_reaper = "CgkIj7XW1fQbEAIQBg"; // <GPGSID>
        public const string achievement_hero_road = "CgkIj7XW1fQbEAIQAg"; // <GPGSID>
        public const string achievement_timebreaker = "CgkIj7XW1fQbEAIQDA"; // <GPGSID>
        public const string achievement_kingslayer = "CgkIj7XW1fQbEAIQCw"; // <GPGSID>
        public const string achievement_craft_master = "CgkIj7XW1fQbEAIQCQ"; // <GPGSID>
        public const string achievement_treasurer = "CgkIj7XW1fQbEAIQAw"; // <GPGSID>
        public const string achievement_first_win = "CgkIj7XW1fQbEAIQAQ"; // <GPGSID>
        public const string event_c_1000 = "CgkIj7XW1fQbEAIQDw"; // <GPGSID>
        public const string achievement_strongger__better = "CgkIj7XW1fQbEAIQBw"; // <GPGSID>
        public const string achievement_impregnable = "CgkIj7XW1fQbEAIQDQ"; // <GPGSID>
        public const string achievement_iron_will = "CgkIj7XW1fQbEAIQBQ"; // <GPGSID>
        public const string achievement_sweet_times = "CgkIj7XW1fQbEAIQCg"; // <GPGSID>

}

